################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Each subdirectory must supply rules for building sources it contributes
espComs.obj: ../espComs.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"/home/chrisn/software/ccsv7/ccsv7/tools/compiler/ti-cgt-msp430_16.9.0.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/home/chrisn/software/ccsv7/ccsv7/ccs_base/msp430/include" --include_path="/home/chrisn/software/ccsv7/ccsv7/tools/compiler/ti-cgt-msp430_16.9.0.LTS/include" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/USB_API" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/F5xx_F6xx_Core_Lib" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/USB_API/USB_CDC_API" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/USB_API/USB_Common" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/USB_API/USB_HID_API" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/USB_API/USB_MSC_API" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/USB_API/USB_PHDC_API" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/USB_config" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/library" --advice:power=all --define=__MSP430F5528__ -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="espComs.d" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

host_interface.obj: ../host_interface.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"/home/chrisn/software/ccsv7/ccsv7/tools/compiler/ti-cgt-msp430_16.9.0.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/home/chrisn/software/ccsv7/ccsv7/ccs_base/msp430/include" --include_path="/home/chrisn/software/ccsv7/ccsv7/tools/compiler/ti-cgt-msp430_16.9.0.LTS/include" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/USB_API" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/F5xx_F6xx_Core_Lib" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/USB_API/USB_CDC_API" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/USB_API/USB_Common" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/USB_API/USB_HID_API" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/USB_API/USB_MSC_API" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/USB_API/USB_PHDC_API" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/USB_config" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/library" --advice:power=all --define=__MSP430F5528__ -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="host_interface.d" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

host_menu.obj: ../host_menu.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"/home/chrisn/software/ccsv7/ccsv7/tools/compiler/ti-cgt-msp430_16.9.0.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/home/chrisn/software/ccsv7/ccsv7/ccs_base/msp430/include" --include_path="/home/chrisn/software/ccsv7/ccsv7/tools/compiler/ti-cgt-msp430_16.9.0.LTS/include" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/USB_API" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/F5xx_F6xx_Core_Lib" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/USB_API/USB_CDC_API" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/USB_API/USB_Common" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/USB_API/USB_HID_API" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/USB_API/USB_MSC_API" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/USB_API/USB_PHDC_API" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/USB_config" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/library" --advice:power=all --define=__MSP430F5528__ -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="host_menu.d" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

main.obj: ../main.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"/home/chrisn/software/ccsv7/ccsv7/tools/compiler/ti-cgt-msp430_16.9.0.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/home/chrisn/software/ccsv7/ccsv7/ccs_base/msp430/include" --include_path="/home/chrisn/software/ccsv7/ccsv7/tools/compiler/ti-cgt-msp430_16.9.0.LTS/include" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/USB_API" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/F5xx_F6xx_Core_Lib" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/USB_API/USB_CDC_API" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/USB_API/USB_Common" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/USB_API/USB_HID_API" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/USB_API/USB_MSC_API" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/USB_API/USB_PHDC_API" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/USB_config" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/library" --advice:power=all --define=__MSP430F5528__ -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="main.d" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

motor.obj: ../motor.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"/home/chrisn/software/ccsv7/ccsv7/tools/compiler/ti-cgt-msp430_16.9.0.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/home/chrisn/software/ccsv7/ccsv7/ccs_base/msp430/include" --include_path="/home/chrisn/software/ccsv7/ccsv7/tools/compiler/ti-cgt-msp430_16.9.0.LTS/include" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/USB_API" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/F5xx_F6xx_Core_Lib" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/USB_API/USB_CDC_API" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/USB_API/USB_Common" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/USB_API/USB_HID_API" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/USB_API/USB_MSC_API" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/USB_API/USB_PHDC_API" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/USB_config" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/library" --advice:power=all --define=__MSP430F5528__ -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="motor.d" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

pins.obj: ../pins.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"/home/chrisn/software/ccsv7/ccsv7/tools/compiler/ti-cgt-msp430_16.9.0.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/home/chrisn/software/ccsv7/ccsv7/ccs_base/msp430/include" --include_path="/home/chrisn/software/ccsv7/ccsv7/tools/compiler/ti-cgt-msp430_16.9.0.LTS/include" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/USB_API" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/F5xx_F6xx_Core_Lib" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/USB_API/USB_CDC_API" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/USB_API/USB_Common" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/USB_API/USB_HID_API" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/USB_API/USB_MSC_API" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/USB_API/USB_PHDC_API" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/USB_config" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/library" --advice:power=all --define=__MSP430F5528__ -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="pins.d" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

scheduler.obj: ../scheduler.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"/home/chrisn/software/ccsv7/ccsv7/tools/compiler/ti-cgt-msp430_16.9.0.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/home/chrisn/software/ccsv7/ccsv7/ccs_base/msp430/include" --include_path="/home/chrisn/software/ccsv7/ccsv7/tools/compiler/ti-cgt-msp430_16.9.0.LTS/include" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/USB_API" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/F5xx_F6xx_Core_Lib" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/USB_API/USB_CDC_API" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/USB_API/USB_Common" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/USB_API/USB_HID_API" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/USB_API/USB_MSC_API" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/USB_API/USB_PHDC_API" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/USB_config" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/library" --advice:power=all --define=__MSP430F5528__ -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="scheduler.d" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

uart.obj: ../uart.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"/home/chrisn/software/ccsv7/ccsv7/tools/compiler/ti-cgt-msp430_16.9.0.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/home/chrisn/software/ccsv7/ccsv7/ccs_base/msp430/include" --include_path="/home/chrisn/software/ccsv7/ccsv7/tools/compiler/ti-cgt-msp430_16.9.0.LTS/include" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/USB_API" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/F5xx_F6xx_Core_Lib" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/USB_API/USB_CDC_API" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/USB_API/USB_Common" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/USB_API/USB_HID_API" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/USB_API/USB_MSC_API" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/USB_API/USB_PHDC_API" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/USB_config" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/library" --advice:power=all --define=__MSP430F5528__ -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="uart.d" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

usbConstructs.obj: ../usbConstructs.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"/home/chrisn/software/ccsv7/ccsv7/tools/compiler/ti-cgt-msp430_16.9.0.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/home/chrisn/software/ccsv7/ccsv7/ccs_base/msp430/include" --include_path="/home/chrisn/software/ccsv7/ccsv7/tools/compiler/ti-cgt-msp430_16.9.0.LTS/include" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/USB_API" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/F5xx_F6xx_Core_Lib" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/USB_API/USB_CDC_API" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/USB_API/USB_Common" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/USB_API/USB_HID_API" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/USB_API/USB_MSC_API" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/USB_API/USB_PHDC_API" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/USB_config" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/library" --advice:power=all --define=__MSP430F5528__ -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="usbConstructs.d" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

usbEventHandling.obj: ../usbEventHandling.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"/home/chrisn/software/ccsv7/ccsv7/tools/compiler/ti-cgt-msp430_16.9.0.LTS/bin/cl430" -vmspx --data_model=restricted --use_hw_mpy=F5 --include_path="/home/chrisn/software/ccsv7/ccsv7/ccs_base/msp430/include" --include_path="/home/chrisn/software/ccsv7/ccsv7/tools/compiler/ti-cgt-msp430_16.9.0.LTS/include" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/USB_API" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/F5xx_F6xx_Core_Lib" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/USB_API/USB_CDC_API" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/USB_API/USB_Common" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/USB_API/USB_HID_API" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/USB_API/USB_MSC_API" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/USB_API/USB_PHDC_API" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/USB_config" --include_path="/home/chrisn/Documents/myRepos/pumpkin/firmware/library" --advice:power=all --define=__MSP430F5528__ -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="usbEventHandling.d" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '


